# This workflow checks the version of the application package that is being
# built in the current pull request. If the version has already been published,
# the workflow fails to prevent PRs from being merged until the version has been
# incremented in the manifest file.
name: Version Check

on:
  pull_request:
    branches:
      - main

env:
  MANIFEST_PATH: package.json

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  check-version:
    name: Version Check
    runs-on: ubuntu-latest

    # Skips Dependabot PRs
    if: ${{ startsWith(github.head_ref, 'dependabot/') == false }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6
        with:
          fetch-tags: true
          fetch-depth: 0

      # Check the version in the manifest file.
      - name: Check Version
        id: check-version
        uses: issue-ops/semver@v2
        with:
          # Allow releasing prerelease versions
          allow-prerelease: true
          # Checks and fails if the version already exists
          check-only: true
          # Add/update a comment on the PR
          comment: true
          # Path to the manifest file with the version information
          manifest-path: package.json
          # Don't overwrite if a version already exists
          overwrite: false
          # Update the repository tag references
          push-tags: true
          # The workspace directory
          workspace: ${{ github.workspace }}
